/* SVice production offline shell — generated by scripts/build-sw.mjs. */
const VERSION = "0bd6dc4936ae49f7";
const SCOPE = self.registration.scope;
const PREFIX = 'svice-shell-' + encodeURIComponent(new URL(SCOPE).pathname) + '-';
const CACHE = PREFIX + VERSION;
const INDEX = new URL('index.html', SCOPE).href;
const ASSETS = [
  "apple-touch-icon.png",
  "assets/index-BetWdTX8.js",
  "assets/index-mQc9QzBm.css",
  "icon-192.png",
  "icon-512.png",
  "icon.svg",
  "index.html",
  "manifest.webmanifest"
].map((file) => new URL(file, SCOPE).href);
const ASSET_SET = new Set(ASSETS);

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) =>
    cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' })))
  ));
  // A new version waits until every open SVice window is closed. This keeps
  // the running page and its cached assets on the same version.
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(PREFIX) && key !== CACHE)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  const scope = new URL(SCOPE);
  if (request.method !== 'GET' || url.origin !== scope.origin ||
      !url.pathname.startsWith(scope.pathname)) return;

  // App navigation uses the same cached shell as its bundled JS/CSS.
  // User records stay in IndexedDB; no record or external site is cached here.
  if (request.mode === 'navigate') {
    event.respondWith(caches.open(CACHE).then(async (cache) =>
      (await cache.match(INDEX)) || fetch(request)
    ));
    return;
  }

  url.search = '';
  url.hash = '';
  if (!ASSET_SET.has(url.href)) return;
  event.respondWith(caches.open(CACHE).then(async (cache) =>
    (await cache.match(url.href)) || fetch(request)
  ));
});
